#!/usr/bin/env bash
# goclaw VPS bootstrap — run ON the server (Ubuntu/Debian).
# Idempotent: safe to re-run. Generates .env on first run.
#
# Usage:
#   GOCLAW_ENCRYPTION_KEY=<from local .env> ./setup.sh   # when migrating data
#   ./setup.sh                                            # fresh install
set -euo pipefail

cd "$(dirname "$0")"

# --- 1. Docker (skip if present) ---
if ! command -v docker >/dev/null 2>&1; then
  echo ">>> Installing Docker..."
  curl -fsSL https://get.docker.com | sh
fi

# --- 2. .env on first run ---
if [ ! -f .env ]; then
  echo ">>> Generating .env..."
  cat > .env <<EOF
# Generated by setup.sh $(date -u +%FT%TZ)
GOCLAW_GATEWAY_TOKEN=$(openssl rand -hex 24)
GOCLAW_ENCRYPTION_KEY=${GOCLAW_ENCRYPTION_KEY:-$(openssl rand -hex 32)}
POSTGRES_USER=goclaw
POSTGRES_PASSWORD=$(openssl rand -hex 16)
POSTGRES_DB=goclaw
EOF
  chmod 600 .env
  echo ">>> .env created. Gateway token:"
  grep GOCLAW_GATEWAY_TOKEN .env
else
  echo ">>> .env exists, keeping it."
fi

# --- 3. Up ---
echo ">>> Pulling and starting..."
docker compose up -d --pull always

echo
echo ">>> Status:"
docker compose ps
echo
echo ">>> Dashboard: http://$(curl -fsS -4 ifconfig.co 2>/dev/null || echo SERVER_IP):18790"
echo ">>> Login token: see GOCLAW_GATEWAY_TOKEN in .env"
